Entity/Page.php
<?php

namespace ScyLabs\NeptuneBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use ScyLabs\NeptuneBundle\AbstractEntity\AbstractElem;
use Symfony\Component\Form\FormFactory;
use Doctrine\ORM\Mapping\OrderBy;
use Doctrine\ORM\Mapping\Annotation;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="ScyLabs\NeptuneBundle\Repository\PageRepository")
 */
class Page extends AbstractElem
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="ScyLabs\NeptuneBundle\Entity\Page", inversedBy="childs")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\Page", mappedBy="parent",orphanRemoval=true,cascade={"persist","remove"})
     * @OrderBy({"prio" = "ASC"})
     */
    private $childs;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\Photo", mappedBy="page",cascade={"persist","remove"})
     * @OrderBy({"prio" = "ASC"})
     */
    protected $photos;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\Document", mappedBy="page",cascade={"persist","remove"})
     * @OrderBy({"prio" = "ASC"})
     */
    protected $documents;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\Video", mappedBy="page",cascade={"persist","remove"})
     * @OrderBy({"prio" = "ASC"})
     */
    protected $videos;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\Zone", mappedBy="page")
     * @OrderBy({"prio" = "ASC"})
     */
    private $zones;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\ElementType",mappedBy="page")
     */
    private $elementTypes;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\PageDetail", mappedBy="page", orphanRemoval=true,cascade={"persist","remove"})
     */
    private $details;

    /**
     * @ORM\ManyToOne(targetEntity="ScyLabs\NeptuneBundle\Entity\PageType", inversedBy="pages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(length=128,unique=true)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\PageUrl", mappedBy="page",cascade={"persist","remove","refresh"})
     */

    private $urls;

    private $elements;


    public function getElements(array $orderBy = array('prio'=>Criteria::ASC),bool $showAll = false){
        if($this->elements === null){
            $this->elements = new ArrayCollection();
            foreach ($this->elementTypes as $elementType){
                foreach ($elementType->getElements() as $element){
                    if( !$this->elements->contains($element)){
                        $this->elements->add($element);
                    }
                }
            }
        }
        $criteria = Criteria::create();
        $criteria->orderBy($orderBy);
        if($showAll !== true){
            $criteria->where(Criteria::expr()->eq('remove',false));
        }

        return $this->elements->matching($criteria);
    }

    public function __construct()
    {
        parent::__construct();
        $this->childs = new ArrayCollection();
        $this->photos = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->zones = new ArrayCollection();
        $this->elements = new ArrayCollection();
        $this->details = new ArrayCollection();
        $this->urls = new ArrayCollection();
        $this->elementTypes = new ArrayCollection();

    }
    public function getId()
    {
        return $this->id;
    }

    /*Fonction de serialization*/


    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }
    public function setRemove(bool $remove): self
    {
        parent::setRemove($remove);

        if($this->childs !== null){
            foreach ($this->childs as $page){
                $page->setRemove($remove);
            }
        }
        return $this;
    }

    /**
     * @return Collection|Page[]
     */
    public function getElementTypes(bool $showAll = false) : Collection
    {
        $criteria = Criteria::create();
        if($showAll !== true){
            $criteria->where(Criteria::expr()->eq('remove',false));
        }
        return $this->elementTypes;
    }

    public function addElementType(ElementType $elementType): self
    {
        if (!$this->elementTypes->contains($elementType)) {
            $this->elementTypes[] = $elementType;
            $elementType->setPage($this);
        }

        return $this;
    }

    public function removeElementType(ElementType $elementType): self
    {
        if ($this->elementTypes->contains($elementType)) {
            // set the owning side to null (unless already changed)
            if ($elementType->getPage() === $this) {
                $elementType->setPage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Page[]
     */
    public function getChilds(): Collection
    {
        return $this->childs;
    }

    public function addChild(Page $child): self
    {
        if (!$this->childs->contains($child)) {
            $this->childs[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(Page $child): self
    {
        if ($this->childs->contains($child)) {
            $this->childs->removeElement($child);
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }



    /**
     * @return Collection|Zone[]
     */
    public function getZones(bool $showAll = false): Collection
    {
        $criteria = Criteria::create();
        $criteria->orderBy(array(
            'prio'=>Criteria::ASC
        ));
        if($showAll !== true){
            $criteria->where(Criteria::expr()->eq('remove',false));
        }

        return $this->zones->matching($criteria);
    }

    public function addZone(Zone $zone): self
    {
        if (!$this->zones->contains($zone)) {
            $this->zones[] = $zone;
            $zone->setPage($this);
        }

        return $this;
    }

    public function removeZone(Zone $zone): self
    {
        if ($this->zones->contains($zone)) {
            $this->zones->removeElement($zone);
            // set the owning side to null (unless already changed)
            if ($zone->getPage() === $this) {
                $zone->setPage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PageDetail[]
     */
    public function getDetails(): Collection
    {
        return $this->details;
    }

    public function addDetail(PageDetail $detail): self
    {
        if (!$this->details->contains($detail)) {
            $this->details[] = $detail;
            $detail->setPage($this);
        }

        return $this;
    }

    public function removeDetail(PageDetail $detail): self
    {
        if ($this->details->contains($detail)) {
            $this->details->removeElement($detail);
            // set the owning side to null (unless already changed)
            if ($detail->getPage() === $this) {
                $detail->setPage(null);
            }
        }

        return $this;
    }

    public function getType(): ?PageType
    {
        return $this->type;
    }

    public function setType(?PageType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getJsonZones(){
        $tab = array();
        if($this->zones->count() > 0){
            foreach ($this->zones as $zone){
                $tab[] =  $zone->getId();
            }
        }
        return json_encode($tab);
    }
    public function getJsonElements(){
        $tab = array();
        if($this->elementTypes->count() > 0){
            foreach ($this->elementTypes as $elementType){
                foreach ($elementType->getElements() as $element){
                    $tab[] = $element->getId();
                }

            }
        }
        return json_encode($tab);
    }

    public function getDetail($locale){
        foreach ($this->details as $detail){
            if($detail->getLang() == $locale){
                return $detail;
            }
        }
        return new PageDetail();
    }

    /**
     * @return Collection|PageUrl[]
     */
    public function getUrls(): Collection
    {
        return $this->urls;
    }

    public function getUrl($locale) : ?PageUrl{
        foreach ($this->urls as $url){
            if($url->getLang() == $locale){
                return $url;
            }
        }
        return null;
    }

    public function addUrl(PageUrl $url): self
    {
        if (!$this->urls->contains($url)) {
            $this->urls[] = $url;
            $url->setPage($this);
        }

        return $this;
    }

    public function removeUrl(PageUrl $url): self
    {
        if ($this->urls->contains($url)) {
            $this->urls->removeElement($url);
            // set the owning side to null (unless already changed)
            if ($url->getPage() === $this) {
                $url->setPage(null);
            }
        }

        return $this;
    }

}

Entity/User.php
<?php

namespace ScyLabs\NeptuneBundle\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping\OrderBy;

/**
 * @ORM\Entity(repositoryClass="ScyLabs\NeptuneBundle\Repository\UserRepository")
 */
class User extends BaseUser
{


    /**
     * @ORM\Column(name="id",type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $civility;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $name;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="boolean")
     */
    private $firstConnexion;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\Photo", mappedBy="user",cascade={"persist","remove"})
     * @OrderBy({"prio" = "ASC"})
     */
    protected $photos;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\Document", mappedBy="user",cascade={"persist","remove"})
     * @OrderBy({"prio" = "ASC"})
     */
    protected $documents;

    /**
     * @ORM\OneToMany(targetEntity="ScyLabs\NeptuneBundle\Entity\Video", mappedBy="user",cascade={"persist","remove"})
     * @OrderBy({"prio" = "ASC"})
     */
    protected $videos;



    private $tmpRole;
    public function setTmpRole(string $role) : self{
        $this->tmpRole = $role;
        return $this;
    }
    public function getTmpRole(){
        return $this->tmpRole;
    }

    public function __construct(){
        if($this->firstConnexion === null){
            $this->firstConnexion = true;
        }
        if($this->enabled === null){
            $this->enabled = true;
        }
    }
    
    public function getId() :?int{
        return $this->id;
    }

    public function getCivility(): ?string
    {
        return $this->civility;
    }

    public function setCivility(?string $civility): self
    {
        $this->civility = $civility;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getFirstConnexion(): ?bool
    {
        return $this->firstConnexion;
    }

    public function setFirstConnexion(bool $firstConnexion): self
    {
        $this->firstConnexion = $firstConnexion;

        return $this;
    }

    public function getEnabled() : bool {
        return $this->enabled;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): ?Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setParent($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getParent() === $this) {
                $photo->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): ?Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setParent($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->contains($document)) {
            $this->documents->removeElement($document);
            // set the owning side to null (unless already changed)
            if ($document->getParent() === $this) {
                $document->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): ?Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setPage($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->contains($video)) {
            $this->videos->removeElement($video);
            // set the owning side to null (unless already changed)
            if ($video->getPage() === $this) {
                $video->setPage(null);
            }
        }

        return $this;
    }

    public function getJsonFiles(){
        $tab = array();
        if($this->photos != null){

            foreach ($this->photos as $photo){
                $tab[] = $photo->getFile()->getId();
            }
        }
        if($this->documents != null){
            foreach ($this->documents as $document){
                $tab[] = $document->getFile()->getId();
            }
        }
        if($this->videos != null){
            foreach ($this->videos as $video){
                $tab[] = $video->getFile()->getId();
            }
        }
        return json_encode($tab);
    }

}

Form/FileForm.php
<?php

namespace ScyLabs\NeptuneBundle\Form;

use ScyLabs\NeptuneBundle\Entity\File;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FileForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('file',FileType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => File::class,
        ]);
    }
}

Resources/views/admin/file/cartouche.html.twig
<li data-id="{{ file.id }}" class="col-lg-2 relative {{ file.type.name }}" data-type="{{ file.type.name }}">
    <ul class="actions">
        <li>
            <a href="{{ asset('uploads/'~file.file)}}" class="fancy" data-fancybox="gallery"><i class="fa fa-search"></i></a>
        </li>
        <li>
            {{ render(controller(
                'ScyLabs\\NeptuneBundle\\Controller\\FileController::deleteAction',
                {'id':file.id}
            )) }}
        </li>
    </ul>

    <span>
        <span class="boxing">

            <i class="fa fa-check centerXY"></i>
            {% if file.type.name == 'photo' %}
                <img src="{{ asset('uploads/'~file.file)
                | thumb(400) }}"/>
            {% else %}
                <i class="fa {% if file.ext == 'pdf' %}
                fa-file-pdf
                {% endif %} centerXY iconFile">
                    {{ file.originalName }}
                </i>
                <span class="name"></span>
            {% endif %}
            <span class="date">{{ file.date.format('d/m/Y')}}</span>

        </span>
    </span>
</li>

Resources/views/admin/file/listing.html.twig
{% extends '@ScyLabsNeptune/admin/layout.html.twig' %}
{% import _self as recursiveMacro %}
{% macro recursiveTabPage(page) %}
    {% import _self as self %}
    {% if page.remove == 0 %}
        <tr data-id="{{ page.id }}" data-type="page" data-files="{{ page.jsonFiles }}" data-zones="{{ page.jsonZones }}" data-elements="{{ page.jsonElements }}">
            <td>
                {{ page.name }}
            </td>
            <td>
                {% if page.parent is not  null %}
                    {{ page.parent.name }}
                {% endif %}
            </td>
        </tr>
        {% if page.childs |length %}
            {% for child in page.childs %}
                {{ self.recursiveTabPage(child) }}
            {% endfor %}
        {% endif %}
    {% endif %}
{% endmacro %}

{% block css %}
    <link rel="stylesheet" href="{{ asset('bundles/scylabsneptune/admin/css/lib/dropzone/dropzone.css') }}"/>
{% endblock %}
{% block js %}
    <script src="{{ asset('bundles/scylabsneptune/admin/js/lib/dropzone/dropzone.js') }}"></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/datatables.min.js') }}></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js') }}></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js') }}></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js') }}></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js') }}></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js') }}></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js') }}></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js') }}></script>
    <script src={{ asset('bundles/scylabsneptune/admin/js/lib/datatables/datatables-init.js') }}></script>

    <script src="{{ asset('bundles/scylabsneptune/admin/js/gallery.js') }}"></script>
{% endblock %}
{% block content %}
    <div id="addfile_form">
        <form action="{{ path('admin_file_upload') }}"
              class="dropzone"
              id="customdropzone"></form>
    </div>

    <h4>Gérez vos fichiers</h4>
    <div class="row">
        <div id="container_cartouches" class="col-md-10 trans500" data-select="[]">
            <form>
                <label>Filtres : </label>
                <select id="filter_type">
                    <option value="all">Tout</option>
                    {% if fileTypes is defined %}
                        {% for type in fileTypes %}
                            <option value="{{ type.name }}">{{ type.title }}</option>
                        {% endfor %}
                    {% endif %}
                </select>
            </form>
            <div class="card">
                <div class="card-body">
                    <ul id="cartouches" class="hack-inline cartouches">
                        {% if files is defined %}
                            {% for file in files %}
                               {% include('@ScyLabsNeptune/admin/file/cartouche.html.twig') %}
                            {% endfor %}
                        {% endif %}

                    </ul>
                </div>

            </div>
        </div>
        <div class="col-md-2 trans500" id="gallery_actions">
            <div class="card">
                <button onclick="$('#addfile_form').slideToggle(500)" class="btn btn-pink m-b-10 m-l-5 show_form">Ajouter des fichiers</button>
                <button id="lier" class="btn btn-pink m-b-10 m-l-5 show_form">Lier</button>
            </div>
            <div id="selection_elements" class="card none">
                <br/>
                <div id="tabs">
                    <ul class="onglets">

                        {% if collection is defined %}
                            {% for key, tab in collection %}
                                <li><a href="#tabs-{{ loop.index }}">{{ key }}</a></li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                    {% for key, tab in collection %}
                        <div id="tabs-{{ loop.index }}">
                                <div class="card">
                                    <div class="card-body">
                                        <table id="myTable" class="table table-bordered table-striped dataTable no-footer" role="grid" aria-describedby="myTable_info">
                                            <thead>
                                            <th>Name</th>
                                            <th>Type</th>
                                            {% if tab | length and tab[0].parent is defined %}
                                                <th>Parent</th>
                                            {% endif %}
                                            </thead>
                                            <tbody>
                                            {% for object in tab %}
                                                {% if key == 'Pages' %}
                                                    {{ recursiveMacro.recursiveTabPage(object) }}
                                                {% else %}
                                                    <tr class="none" data-files="{{ object.jsonFiles }}" data-type="{{ key | trim('s', 'right') | lower  }}" data-id="{{ object.id }}">
                                                        <td>{{ object.name }}</td>
                                                        <td>{{ object.type.name }}</td>
                                                        {% if object.parent is defined %}
                                                            <td>{{ object.parent.name }}</td>
                                                        {% endif %}
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                        </div>
                    {% endfor %}
                </div>
                <button id="valider_liaison" class="btn btn-pink m-b-10 m-l-5" data-action="{{ path('admin_file_link') }}">Valider</button>
            </div>

        </div>
    </div>
{% endblock %}